/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as AuthenticatedConfiguracionRouteRouteImport } from './routes/_authenticated/configuracion/route'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedRadicadosApiIndexRouteImport } from './routes/_authenticated/radicados-api/index'
import { Route as AuthenticatedMetricasModeloIndexRouteImport } from './routes/_authenticated/metricas-modelo/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedConfiguracionIndexRouteImport } from './routes/_authenticated/configuracion/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAuditorIaIndexRouteImport } from './routes/_authenticated/auditor-ia/index'
import { Route as AuthenticatedRadicadosApiRadicadoRouteImport } from './routes/_authenticated/radicados-api/$radicado'
import { Route as AuthenticatedConfiguracionClaveApiRouteImport } from './routes/_authenticated/configuracion/clave-api'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracionRouteRoute =
  AuthenticatedConfiguracionRouteRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadicadosApiIndexRoute =
  AuthenticatedRadicadosApiIndexRouteImport.update({
    id: '/radicados-api/',
    path: '/radicados-api/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetricasModeloIndexRoute =
  AuthenticatedMetricasModeloIndexRouteImport.update({
    id: '/metricas-modelo/',
    path: '/metricas-modelo/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracionIndexRoute =
  AuthenticatedConfiguracionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConfiguracionRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditorIaIndexRoute =
  AuthenticatedAuditorIaIndexRouteImport.update({
    id: '/auditor-ia/',
    path: '/auditor-ia/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRadicadosApiRadicadoRoute =
  AuthenticatedRadicadosApiRadicadoRouteImport.update({
    id: '/radicados-api/$radicado',
    path: '/radicados-api/$radicado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracionClaveApiRoute =
  AuthenticatedConfiguracionClaveApiRouteImport.update({
    id: '/clave-api',
    path: '/clave-api',
    getParentRoute: () => AuthenticatedConfiguracionRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/configuracion': typeof AuthenticatedConfiguracionRouteRouteWithChildren
  '/sign-in-2': typeof authSignIn2Route
  '/configuracion/clave-api': typeof AuthenticatedConfiguracionClaveApiRoute
  '/radicados-api/$radicado': typeof AuthenticatedRadicadosApiRadicadoRoute
  '/auditor-ia/': typeof AuthenticatedAuditorIaIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/configuracion/': typeof AuthenticatedConfiguracionIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/metricas-modelo/': typeof AuthenticatedMetricasModeloIndexRoute
  '/radicados-api/': typeof AuthenticatedRadicadosApiIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in-2': typeof authSignIn2Route
  '/': typeof AuthenticatedIndexRoute
  '/configuracion/clave-api': typeof AuthenticatedConfiguracionClaveApiRoute
  '/radicados-api/$radicado': typeof AuthenticatedRadicadosApiRadicadoRoute
  '/auditor-ia': typeof AuthenticatedAuditorIaIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/configuracion': typeof AuthenticatedConfiguracionIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/metricas-modelo': typeof AuthenticatedMetricasModeloIndexRoute
  '/radicados-api': typeof AuthenticatedRadicadosApiIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRouteRouteWithChildren
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/configuracion/clave-api': typeof AuthenticatedConfiguracionClaveApiRoute
  '/_authenticated/radicados-api/$radicado': typeof AuthenticatedRadicadosApiRadicadoRoute
  '/_authenticated/auditor-ia/': typeof AuthenticatedAuditorIaIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/configuracion/': typeof AuthenticatedConfiguracionIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/metricas-modelo/': typeof AuthenticatedMetricasModeloIndexRoute
  '/_authenticated/radicados-api/': typeof AuthenticatedRadicadosApiIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracion'
    | '/sign-in-2'
    | '/configuracion/clave-api'
    | '/radicados-api/$radicado'
    | '/auditor-ia/'
    | '/chats/'
    | '/configuracion/'
    | '/help-center/'
    | '/metricas-modelo/'
    | '/radicados-api/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in-2'
    | '/'
    | '/configuracion/clave-api'
    | '/radicados-api/$radicado'
    | '/auditor-ia'
    | '/chats'
    | '/configuracion'
    | '/help-center'
    | '/metricas-modelo'
    | '/radicados-api'
    | '/tasks'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/configuracion'
    | '/(auth)/sign-in-2'
    | '/_authenticated/'
    | '/_authenticated/configuracion/clave-api'
    | '/_authenticated/radicados-api/$radicado'
    | '/_authenticated/auditor-ia/'
    | '/_authenticated/chats/'
    | '/_authenticated/configuracion/'
    | '/_authenticated/help-center/'
    | '/_authenticated/metricas-modelo/'
    | '/_authenticated/radicados-api/'
    | '/_authenticated/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignIn2Route: typeof authSignIn2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radicados-api/': {
      id: '/_authenticated/radicados-api/'
      path: '/radicados-api'
      fullPath: '/radicados-api/'
      preLoaderRoute: typeof AuthenticatedRadicadosApiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metricas-modelo/': {
      id: '/_authenticated/metricas-modelo/'
      path: '/metricas-modelo'
      fullPath: '/metricas-modelo/'
      preLoaderRoute: typeof AuthenticatedMetricasModeloIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion/': {
      id: '/_authenticated/configuracion/'
      path: '/'
      fullPath: '/configuracion/'
      preLoaderRoute: typeof AuthenticatedConfiguracionIndexRouteImport
      parentRoute: typeof AuthenticatedConfiguracionRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditor-ia/': {
      id: '/_authenticated/auditor-ia/'
      path: '/auditor-ia'
      fullPath: '/auditor-ia/'
      preLoaderRoute: typeof AuthenticatedAuditorIaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radicados-api/$radicado': {
      id: '/_authenticated/radicados-api/$radicado'
      path: '/radicados-api/$radicado'
      fullPath: '/radicados-api/$radicado'
      preLoaderRoute: typeof AuthenticatedRadicadosApiRadicadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion/clave-api': {
      id: '/_authenticated/configuracion/clave-api'
      path: '/clave-api'
      fullPath: '/configuracion/clave-api'
      preLoaderRoute: typeof AuthenticatedConfiguracionClaveApiRouteImport
      parentRoute: typeof AuthenticatedConfiguracionRouteRoute
    }
  }
}

interface AuthenticatedConfiguracionRouteRouteChildren {
  AuthenticatedConfiguracionClaveApiRoute: typeof AuthenticatedConfiguracionClaveApiRoute
  AuthenticatedConfiguracionIndexRoute: typeof AuthenticatedConfiguracionIndexRoute
}

const AuthenticatedConfiguracionRouteRouteChildren: AuthenticatedConfiguracionRouteRouteChildren =
  {
    AuthenticatedConfiguracionClaveApiRoute:
      AuthenticatedConfiguracionClaveApiRoute,
    AuthenticatedConfiguracionIndexRoute: AuthenticatedConfiguracionIndexRoute,
  }

const AuthenticatedConfiguracionRouteRouteWithChildren =
  AuthenticatedConfiguracionRouteRoute._addFileChildren(
    AuthenticatedConfiguracionRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracionRouteRoute: typeof AuthenticatedConfiguracionRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedRadicadosApiRadicadoRoute: typeof AuthenticatedRadicadosApiRadicadoRoute
  AuthenticatedAuditorIaIndexRoute: typeof AuthenticatedAuditorIaIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedMetricasModeloIndexRoute: typeof AuthenticatedMetricasModeloIndexRoute
  AuthenticatedRadicadosApiIndexRoute: typeof AuthenticatedRadicadosApiIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracionRouteRoute:
    AuthenticatedConfiguracionRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedRadicadosApiRadicadoRoute:
    AuthenticatedRadicadosApiRadicadoRoute,
  AuthenticatedAuditorIaIndexRoute: AuthenticatedAuditorIaIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedMetricasModeloIndexRoute: AuthenticatedMetricasModeloIndexRoute,
  AuthenticatedRadicadosApiIndexRoute: AuthenticatedRadicadosApiIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignIn2Route: authSignIn2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
